version: '3.0'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  oauth2:
    build: .
    links:
      - redis:redis
    ports:
      - "8080:8080"
    volumes:
      - ./etc/config.sample.toml:/etc/config.toml

  jwkgen:
    build: ./jwkgen
