FROM golang:latest
  WORKDIR /go/src/github.com/DatapuntAmsterdam/goauth2
  COPY . /go/src/github.com/DatapuntAmsterdam/goauth2
  RUN go get github.com/sparrc/gdm
  RUN gdm restore
  RUN go test ./...

