### OAuth 2.0 service configuration file

# bind-host = ""
## Bind to host for the HTTP service (default 0.0.0.0)
# bind-port = 8080
## Bind to this port (default 8080)

base-url = "http://localhost:8080/"
## Base URL of the service. Defaults to http://[bind-address]/.

# pprof-enabled = true
## Enable profiler

# authn-timeout = 600
## This is how many second an end-user has to authenticate, ie between starting and finishing the authz request

# trace-header-name = "X-Unique-ID"
## Name of request race header

# log-json-output = false
## Logs are output as JSON for easier parsing

[accesstoken]
jwk-set = """
{ "keys": [
  { "kty": "oct",
    "alg": "HS256",
    "kid": "1",
    "k":"makemehardtoguess"
  },
  { "kty": "EC",
    "use": "sig",
    "kid": "2",
    "crv": "P-256",
    "x": "g9IULlEyYGp3i2IZ1STiuDQ0rcrt3r3o-01f7_wOM_o=",
    "y": "8QfpzSUvN4UAI4PliUXpeOv8RwLU8P8qLXqhTCc4w1M=",
    "d": "dIz2ALAunAxB5ajQVx3fAdbttNX4WazEyvXLyi6BFBc="
  }
]}
"""
# jwk-id = "1"
## The key id (kid) of the JWK to use when creating access tokens. Defaults to the first key in the set.
## JSON Web Key Set: mandatory, should be a JWKS containing HMAC and / or ECDSA keys as specified in RFC 7517 and RFC 7518 section 6
# lifetime = 36000
## Lifetime of access tokens
# issuer = "http://localhost:8080/authorize"
## Identifier of the token issuer (e.g. URI of authorizatuon endpoint)


[redis]
## Connection params for Redis. An empty password won't AUTH.
# address = ":6379"
# password = ""


[idp]
## IdP configuration
base-url = "https://acc.api.data.amsterdam.nl/auth/idp/login"
api-key = "apikey"
## api-key is authz_admin_api_key_(acc|prod) in ansible-vault
secret = "idp-signkey"
## secret is refreshtoken_key_(acc|prod) in ansible-vault
accounts-url = "https://acc.api.data.amsterdam.nl/authz_admin/accounts/"


[clients]
# OAuth 2.0 clients. Require client-id, granttype and redirects.

[clients."citydata"]
redirects = ["http://localhost:8080/"]
granttype = "token"  # "code" | "token" | "client_credentials"

[authorization]
## Authorization configuration.
base-url = "https://acc.api.data.amsterdam.nl/authz_admin/"
update-interval = 600
