### OAuth 2.0 service configuration file

# Bind address to use for the HTTP service
# bind-address = ":8080"


# Redis connection params
# [redis]
# host = "localhost"
# port = 6379
# password = ""


# Identity providers, schemaless config. Comment out / remove the ones you don't need.
[idp.datapunt]
url = "https://api.data.amsterdam.nl/auth/idp/login"


# OAuth 2.0 clients. Require client-id and redirects. client-secret optional.
[client."citydata-data.amsterdam.nl"]
redirects = ["http://localhost:8080/"]

