### OAuth 2.0 service configuration file

# bind-host = ""
## Bind to host for the HTTP service (default 0.0.0.0)
# bind-port = 8080
## Bind to this port (default 8080)

# base-url = 
# Base URL of the service. Defaults to http://[bind-address]/.

[accesstoken]
secret = "makemehardtoguess"
# Secret used to sign (HMAC-SHA256) access and refresh tokens.
lifetime = 36000
# Lifetime of access tokens
issuer = "http://localhost:8080/authorize"
# Identifier of the token issuer (e.g. URI of authorizatuon endpoint)


[redis]
## Connection params for Redis. An empty password won't AUTH.
address = ":6379"
password = ""


[idp]
## IdP configuration
base-url = "https://acc.api.data.amsterdam.nl/auth/idp/login"
secret = "sharedsecret"
roles-url = "https://acc.api.data.amsterdam.nl/authz_admin/accounts/"


[clients]
# OAuth 2.0 clients. Require client-id, granttype and redirects.

[clients."citydata-data.amsterdam.nl"]
redirects = ["http://localhost:8080/"]
granttype = "token"  # "code" | "token" | "client_credentials"

[authorization]
# Authorization configuration.
base-url = "https://acc.api.data.amsterdam.nl/authz_admin/"

