### OAuth 2.0 service configuration file

# bind-host = ""
## Bind to host for the HTTP service (default 0.0.0.0)
# bind-port = 8080
## Bind to this port (default 8080)

base-url = "http://localhost:8080/"
## Base URL of the service. Defaults to http://[bind-address]/.

# pprof-enabled = true
## Enable profiler

# [accesstoken]
# secret = "makemehardtoguess"
## Secret used to sign (HMAC-SHA256) access and refresh tokens. secret is accesstoken_key_(acc|prod) in ansible-vault
# lifetime = 36000
## Lifetime of access tokens
# issuer = "http://localhost:8080/authorize"
## Identifier of the token issuer (e.g. URI of authorizatuon endpoint)


# [redis]
## Connection params for Redis. An empty password won't AUTH.
# address = ":6379"
# password = ""


[idp]
## IdP configuration
base-url = "https://acc.api.data.amsterdam.nl/auth/idp/login"
api-key = "key"
## api-key is authz_admin_api_key_(acc|prod) in ansible-vault
secret = "sharedsecret"
## secret is refreshtoken_key_(acc|prod) in ansible-vault
accounts-url = "https://acc.api.data.amsterdam.nl/authz_admin/accounts/"


[clients]
# OAuth 2.0 clients. Require client-id, granttype and redirects.

[clients."citydata"]
redirects = ["http://localhost:8080/"]
granttype = "token"  # "code" | "token" | "client_credentials"

[authorization]
## Authorization configuration.
base-url = "https://acc.api.data.amsterdam.nl/authz_admin/"

